### PR TITLE
[t2cstr] move _t2cCtx off the stack (and init with zeros)

### PR DESCRIPTION
**Pull request by cjchapman**
The structure `_t2cCtx` is about 600k in size and thus should be in the heap, not on the stack, hence this change. (Also added a `memset` to explicitly initialize it full of zeros.)

### CODE REVIEW

**Comment by cjchapman** [comment]
I think Codacy is confused by the `DURING_EX` ... `HANDLER` ... `END_HANDLER` macros in this block:
```
    DURING_EX(h->err.env)

    retVal = t2Decode(h, offset);

    HANDLER
    retVal = Exception.Code;
    END_HANDLER
```

**Comment by readroberts** [comment]
@cjchapman Can you point me to where the malloc'd _t2cCtx gets freed?

**Comment by cjchapman** [comment]
@readroberts I can, now that I've amended the commit. :wink: Thanks for catching this.
(I also removed a couple of apparently superfluous lines.)

**Comment by cjchapman** [comment]
I'm guessing it's the  `END_HANDLER` macro that's confusing Codacy into thinking that `free()` is a variable. 🤦‍♂

**Pull request merged**
