### PR TITLE
clean up autohint

### PR DESCRIPTION
**Pull request by cjchapman**
Used `clang-format` to do some automated reformatting of the autohint code, followed by some manual editing to clean up the remaining issues identified by `cpplint`.

### CODE REVIEW

**Comment by cjchapman** [comment]
@anthrotype & @khaledhosny Sorry that I accidentally blew away your comments when I force-pushed the commit history change that @miguelsousa wanted.

By the way, I found a tool called `cproto` (which I haven't used in this branch), which can convert old K&R style function declarations into the modern ANSI style.

For example, to modernize the declarations in `afdko/c/autohint/autohintlib/source/ac/fix.c`, the command:
```bash
cproto -a -I ../public/ac -I ../bf -I ../public/extras -I /Applications/Xcode.app//Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys fix.c
```
converts a declaration like this:
```C
private
procedure
CheckForNearBands(loc, blues, numblues)
    Fixed loc,
    *blues;
    integer numblues;
{
```
into something like this:
```C
private
procedure
CheckForNearBands(Fixed loc, Fixed *blues, integer numblues) {
```

**Comment by miguelsousa** [comment]
@cjchapman the comments are still here https://github.com/adobe-type-tools/afdko/commit/ac6ec315271f88b90e8a788b5851bb1fcd4489f2#commitcomment-29841073

**Comment by cjchapman** [comment]
@miguelsousa Ah, OK. Thanks!

**Comment by khaledhosny** [comment]
I used `cproto` in psautohint, it have been extremely laborious to fix old-style function prototypes otherwise. Fixing this unmasked many potential bugs from calling functions with the wrong arguments since now compilers can discover and complain about them.

**Pull request merged**
