### PR TITLE
travis: set 'language: python' else Travis thinks this is Ruby...

### PR DESCRIPTION
**Pull request by anthrotype**
https://travis-ci.org/adobe-type-tools/afdko/jobs/368822577#L474

### CODE REVIEW

**Comment by anthrotype** [comment]
Still failing.. this time the log seems truncated, can’t see any errors. Try click rebuild?

**Comment by cjchapman** [comment]
I'm getting a timeout when I try to connect to Travis right now.

**Comment by cjchapman** [comment]
OK, finally connected. Just hit restart. (I'm using my cellular connection on a train, which might be part of the problem.)

**Comment by cjchapman** [comment]
@anthrotype Looks like it failed again, and again the log seems truncated, even the raw log.

**Pull request merged**
