### PR TITLE
[tx] Fix for issues 353 (tx assumed that a CFF2 font is a variable fo…

### PR DESCRIPTION
**Pull request by readroberts**
…nt) and 354 (tx had an array overflow with many hints).

1) Not only did tx assume that in a CFF2 table, the VariationStore is non-zero, it also did not not check in other places.
2) The array allotted for blended arguments was sized only for path operations, and was not large enough for stem arguments.

### CODE REVIEW

**Comment by miguelsousa** [comment]
I've changed the base branch to be `develop` instead of `master`.

**Comment by miguelsousa** [comment]
@readroberts what's the status on this PR?

**Comment by readroberts** [comment]
I just forgot about it. Will deal with this when I get back from work on Weds.

**Comment by readroberts** [comment]
Noted. Will get to  Tues-Weds this week.

**Pull request closed without merging**
