### PR TITLE
Fixes and improvements to GH Actions

### PR DESCRIPTION
**Pull request by miguelsousa**
Makes a few fixes and improvements to the Test and Publish workflows, now that the whole infrastructure is a bit more mature.

References that may help with reviewing these changes:
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
- https://github.com/pypa/gh-action-pypi-publish
- https://github.com/softprops/action-gh-release
- https://github.com/actions/create-release

### CODE REVIEW

**Comment by miguelsousa** [comment]
This PR needs more work. The release should be created only after all the wheels have been built.

At the end of each platform run the build artifacts should be uploaded. Afterwards the job that creates the release will download the whole set of wheels and publish them to PyPI and GH. Documentation on storing workflow data as artifacts https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts

**Comment by miguelsousa** [comment]
I think this PR is now ready for review. I've tested the new changes by using this repo https://github.com/miguelsousa/test-workflows/

These are some more references I had to use:
- https://github.com/actions/upload-artifact
- https://github.com/actions/download-artifact
- https://github.com/actions/checkout
- https://zxq9.com/archives/795
- https://unix.stackexchange.com/questions/48101/how-can-i-have-date-output-the-time-from-a-different-timezone
- https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Review by josh-hadley — APPROVED** [review]
Great, thanks for getting this updated -- should be useful for other projects as well.

N.B. I saw that the Coverage-related tests are failing, I believe that's because they're picking up the newer fontTools release upon install and failing for the same reasons as https://github.com/adobe-type-tools/afdko/pull/1341 (TTX-related). I think @kaydeearts has some updates in the works for those so we should be able to get this all sorted out soon.

**Review by kaydeearts — APPROVED** [review]
👍  Rebased & now tests are passing. Josh had given an approval before the rebase as well, so now it's good to go.

**Pull request merged**
