### PR TITLE
Adding checks to doFamilyTest18 to avoid traceback

### LINKED ISSUE #1593: [comparefamily]  doFamilyTest18 should skip rest of tests if there are no bluezones
I accidentally ran a font through comparefamily without any blue zones. It correctly prints the error on Line 4093:
https://github.com/adobe-type-tools/afdko/blob/feebd77d9b6507a0b32f837535511be3c94d9c6f/python/afdko/comparefamily.py#L4091-L4095

but then continues on to line 4104, which tries to take an index of an empty list.

```
Traceback (most recent call last):
  File "/Users/colinmford/MyFont/.venv/bin/compareFamily", line 8, in <module>
    sys.exit(main())
  File "/Users/colinmford/MyFont/.venv/lib/python3.10/site-packages/afdko/comparefamily.py", line 5028, in main
    doFamilyTests(singleTestList, familyTestList)
  File "/Users/colinmford/MyFont/.venv/lib/python3.10/site-packages/afdko/comparefamily.py", line 4377, in doFamilyTests
    doFamilyTest18()
  File "/Users/colinmford/MyFont/.venv/lib/python3.10/site-packages/afdko/comparefamily.py", line 4104, in doFamilyTest18
    if tempBlues[1] < font.fontBBox[1]:
IndexError: list index out of range
```

https://github.com/adobe-type-tools/afdko/blob/feebd77d9b6507a0b32f837535511be3c94d9c6f/python/afdko/comparefamily.py#L4104-L4105

The function should probably be restructured around line 4101 to not continue if any of the tests above it (no zones, zones with values of zero, more than 14 zones, or an odd number of zones) fail.

### PR DESCRIPTION
**Pull request by colinmford**
Adding checks to doFamilyTest18 to ensure `tempBlues` has values before continuing, in order to avoid a traceback.

## Description

Fixes #1593.

As noted in the issue, if the font lacks blue values, `compareFamily` reports that correctly. But then it continues on until it tries to take the index of the empty list, which results in a traceback. This PR adds a few if statements to make sure `tempBlues` has length before continuing to those checks. If it doesn't, those checks are skipped because they do not apply.

## Checklist:

- [x] I have followed the [Contribution Guidelines](https://github.com/adobe-type-tools/afdko/blob/develop/CONTRIBUTING.md)
- [ ] I have added **test code and data** to prove that my code functions correctly
- [x] I have verified that new and existing tests pass locally with my changes
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by colinmford** [comment]
Sorry! I just re-synced the branches! We can try again!

**Comment by josh-hadley** [comment]
@colinmford sorry to be a pain but I want to make sure we get the coverage and test suites to run and we're hitting some weirdness in GitHub with external contributions like yours. Could I ask you to close this PR and start a new one from a fresh branch (of our latest `develop`)? Doing that should re-trigger a prompt (for us) to re-run the test suite, which we'll do and if all is well we can get your changes in.

**Comment by colinmford** [comment]
@josh-hadley Sure, no problem, will do on Monday! Thanks!

**Comment by josh-hadley** [comment]
Awesome, thanks! And again, sorry this has been such a hassle.

**Pull request closed without merging**
