### PR TITLE
appveyor: deploy windows wheel on tagged commits

### PR DESCRIPTION
**Pull request by anthrotype**
you should replace the pypi credentials and encrypt the password by going to 'Account → Encrypt data' tool on Appveyor website

see https://www.appveyor.com/docs/build-configuration/#secure-variables

### CODE REVIEW

**Comment by anthrotype** [comment]
appveyor also provides the built artifacts for each build, which is nice
https://ci.appveyor.com/project/adobe-type-tools/afdko/build/1.0.83/artifacts

**Comment by anthrotype** [comment]
travis linux build failed for random unrelated network issues, try reloading the build and it should fix itself

**Comment by miguelsousa** [comment]
Just restarted Travis. Will look into Appveyor once I get to my desk.

**Comment by miguelsousa** [comment]
@anthrotype after merging I added a new tag `2.27.0a2`, but the Windows deployment didn't happen. Not sure where to look for the error, or if there's something misconfigured in AppVeyor's settings.

**Comment by anthrotype** [comment]
the latest build has:

https://ci.appveyor.com/project/adobe-type-tools/afdko#L10027

> Not deploying as this is not a tagged commit

also in the https://ci.appveyor.com/project/adobe-type-tools/afdko/history, all the builds seems to be from master branch and no tags are shown.

I could be some settings that says only build from master or similar.

I have this in my projects' appveyor settings

screenshot 2018-04-18 22 07 19

**Comment by anthrotype** [comment]
i remember with @cjchapman we realised that Travis CI was interpreting git tags as if they were different branches, so when only enabling the building from master, we were also excluding the tag "branches", so we had to change the travis settings to also allow building from branches that matches a pattern (`\d+\.\d+\.\d+.*`)

**Comment by miguelsousa** [comment]
Branches to build is set to "All branches" as well.
What about in **Deployment**? Did you set any deployment provider?

**Comment by anthrotype** [comment]
maybe try use the same regexp that you use for travis

screenshot 2018-04-18 22 12 45

https://www.appveyor.com/docs/branches/

**Comment by anthrotype** [comment]
no, I don't set up any deployment setting from the appveyor website.

**Comment by miguelsousa** [comment]
I've specified the branches to build, and replaced the tag on the last commit (https://github.com/adobe-type-tools/afdko/tags). Nothing seems to have happened. Perhaps need to make a new commit.

**Comment by anthrotype** [comment]
> Branches to build is set to "All branches" as well.

hm.. you sure? this is weird. It seems to only build master, there are no other branches nor tags listed in the build history.

> All branches are built by default. [...]
> By default AppVeyor starts a new build on any push to GitHub, whether it’s a regular commit or a new tag.

**Comment by anthrotype** [comment]
> Perhaps need to make a new commit.

totally, yes.

git commit --allow-empty -m "Something"

**Comment by miguelsousa** [comment]
Done 🤞

**Comment by anthrotype** [comment]
try adding this to .appveyor.yml (same as the one you have in .travis.yml)

```yaml
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+.*$/
```

**Pull request merged**
