### PR TITLE
Update ufoLib to v3.0.0

### PR DESCRIPTION
**Pull request by miguelsousa**

### CODE REVIEW

**Comment by anthrotype** [comment]
:crossed_fingers:

**Comment by anthrotype** [comment]
ok that failure is a known one, but believe me it's a _feature_ ;)
https://travis-ci.org/adobe-type-tools/afdko/jobs/440211784#L2126

basically makeinstancesufo or mutatorMath (not sure) it attempting to write a UFO whose parent directory doesn't exist. Previously ufoLib would silently create all the directory tree (as in `mkdir -p`), now it fails with an error ("Cannot write to ...; the directory does not exist"), which is the right thing to do. 

See https://github.com/unified-font-object/ufoLib/issues/60

**Comment by anthrotype** [comment]
this other failure is because checkoutlinesufo.py is modifying the `UFOWriter.layerContents` dictionary using a `bytes` string as the key (line 139, the global variable `PROCD_GLYPHS_LAYER_NAME`).
It should use unicode string instead, because the pyfilesystem2 API only accepts unicode strings for path names.

https://travis-ci.org/adobe-type-tools/afdko/jobs/440211784#L1518

**Comment by miguelsousa** [comment]
I was going to submit a patch to **mutatorMath** for the directory tree creation problem, but I think a better move for **afdko** is to resume the work on #402.

**Comment by anthrotype** [comment]
that sounds like a better plan. but ufoProcessor will have the same problem

**Pull request closed without merging**
