### PR TITLE
[makeotf] Allow anonymous glyphclass in LookupFlags

### PR DESCRIPTION
**Pull request by khaledhosny**
## Description

Almost everywhere else when a glyph class name is accepted, anonymous glyph classes are also accepted. This is rather inconsistent and inconvenient

## Checklist:

- [x] I have followed the [Contribution Guidelines](https://github.com/adobe-type-tools/afdko/blob/develop/CONTRIBUTING.md)
- [x] I have added **test code and data** to prove that my code functions correctly
- [x] I have verified that new and existing tests pass locally with my changes
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by cjchapman** [comment]
Looks like Travis passed, but never got back to GitHub about it:
https://travis-ci.org/github/adobe-type-tools/afdko/builds/715929569

**Comment by khaledhosny** [comment]
> Looks like Travis passed, but never got back to GitHub about it:
> https://travis-ci.org/github/adobe-type-tools/afdko/builds/715929569

Something is broken with Travis indeed, I force pushed to re-trigger the build but the same happened again. Build https://travis-ci.org/github/adobe-type-tools/afdko/builds/716378446 passes but it does not report it here.

**Comment by cjchapman** [comment]
@khaledhosny Yes, Travis is definitely broken. We're seeing the same problem in other PRs. Josh is working on using GitHub Actions instead of Travis CI so that we can drop Travis.

**Comment by khaledhosny** [comment]
> 4d-8 and 4d-10 are the exact same. Was one meant to do MarkAttachmentType and the other UseMarkFilteringSet?

Yes, fixed.

**Pull request merged**
