### PR TITLE
testing continuous integration

### PR DESCRIPTION
**Pull request by cjchapman**
this is just a test of the continuous integration systems, please do not merge

### CODE REVIEW

**Comment by cjchapman** [comment]
@anthrotype This is the PR in which @miguelsousa and I are experimenting, as I mentioned on Gitter.

**Comment by anthrotype** [comment]
try updating to the latest cibuildwheel from upstream (0.10.0). It worked for me on trufont/uharfbuzz repo

**Comment by miguelsousa** [comment]
@anthrotype I don't see why that would make any difference, but I'll try. One noteworthy difference between afdko and uharfbuzz is that we build py27 wheels.

**Comment by anthrotype** [comment]
why do you think it's related to wheel==0.32? If I look at the travis build logs, the wheel seems to be compiled successfully (or at least it doesn't error out), but then some assertions fail in the tests, as the generated output is different from the expected one..

**Comment by anthrotype** [comment]
oh I see now:
https://travis-ci.org/adobe-type-tools/afdko/jobs/436340698#L315

delocate is failing with wheel==0.32.0

you need to pin wheel==0.31.1 in the `pyproject.toml`, under `[build-system] requires`. That should fix it. I did the same with uharfbuzz.

**Comment by miguelsousa** [comment]
@anthrotype thanks, that's the bit I was missing.
@cjchapman closing this PR in favor of #637.

**Comment by cjchapman** [comment]
@miguelsousa OK. I went ahead and deleting the test branch too.

**Pull request closed without merging**
