### PR TITLE
[autohint] Fix temp files solution

### LINKED ISSUE #244: [autohint] conflict problem when run simultaneously
Looking at autohint.py
````python
	# temp file names for input and output bez files, and for the fontinfo file.
	tempBaseName = os.path.join(tempfile.gettempdir(), "fdkautohint")
	tempBez = tempBaseName + ".bez"
	tempBezNew = tempBez + ".new"
	tempFI = tempBaseName + ".fi"
````

This seems fixed name temp file is created, causing conflicts when multiple
autohint programs run simultaneously.  It may be better create the temp file name
with proper procedure (e.g. use tempfile) .

### PR DESCRIPTION
**Pull request by miguelsousa**
Fixes #244

### CODE REVIEW

**Comment by miguelsousa** [comment]
@cjchapman `autohint` is due to be replaced with `psautohint`. I don't think the fixes and clean ups you listed are worth doing.

**Comment by cjchapman** [comment]
@miguelsousa OK. For the record, I'm approving this PR on the basis that the issues I'm concerned about are not in the areas changed by the PR.  :-)

**Comment by miguelsousa** [comment]
@cjchapman don't worry, these shaddy approvals shall not taint your reputation 😜

**Comment by cjchapman** [comment]
@miguelsousa It's the whole public record thing that worries me, e.g. what if my daughter reads this someday and says, "Seriously Dad, you approved _this_?!" :wink:

**Pull request merged**
