### PR TITLE
update instructions for installing from source

### PR DESCRIPTION
**Pull request by cjchapman**
resolves https://github.com/adobe-type-tools/afdko/issues/675
[no CI]

### CODE REVIEW

**Comment by frankrolf** [comment]
I was about to ask “Are we really removing the simple `python setup.py install` – which works for Python 2”, but then I realized we probably don’t want to encourage Python 2 use anyway.

**Comment by cjchapman** [comment]
The wheel-based instructions work for both Python 2 & 3.

The basic install instructions don't work because they're meant for Python-only installation, not the sort of hybrid C-binaries + Python installation that we're doing. At least, that's my understanding of the problem.

**Comment by anthrotype** [comment]
the only thing really missing from this wheel-based setup is the ability to pip install in --editable mode, which is the same as doing `python setup.py develop`. But this only impacts the few core afdko developers that need to work on the sources as they modify them, and they can use alternative methods like exporting a PYTHONPATH, or using .pth file or similar hacks

**Comment by anthrotype** [comment]
i'd suggest something like:
```
ensure the `wheel` module is installed (`pip install wheel`), then cd to the top-level directory of the afdko, and run:
    pip install .
```

**Comment by anthrotype** [comment]
bonus point, with an additional note saying that `pip install -e .` doesn't work for the reasons explained above.

**Comment by cjchapman** [comment]
@miguelsousa and @anthrotype I don't understand what you guys are talking about and I'm trying to focus on the refactoring of tx, rotatefont, & mergefonts right now, so I'd be grateful if one of you could update the readme with whatever wording you think is appropriate.

**Comment by miguelsousa** [comment]
Will do.

**Pull request closed without merging**
