### PR TITLE
cleaned up xcode build warnings

### PR DESCRIPTION
**Pull request by cjchapman**
(mostly a port of fixes from tx.c)

### CODE REVIEW

**Comment by cjchapman** [comment]
I'd definitely like to consolidate the shared code, preferably sooner rather than later, but not as soon as this PR. Do we already have an issue about consolidating the code? Let me know if not, and I can create one. It's a bit more work than a simple clean up PR like this.

Also, I've got another set of changes to remove some more unused code that I'd like to commit after we merge this PR (removing some other files, with some implications for these files).

**Comment by miguelsousa** [comment]
There's no open issue about code consolidation.

**Comment by cjchapman** [comment]
There is now: https://github.com/adobe-type-tools/afdko/issues/665

**Comment by cjchapman** [comment]
I had to redeliver the AppVeyor delivery just now to kick off its PR review.

**Pull request merged**
