### PR TITLE
[build_wheels.yml] Update to manylinux2014 (CentOS7), use BEFORE_ALL_LINUX

### PR DESCRIPTION
**Pull request by kaydeearts**

### CODE REVIEW

**Review by cjchapman — APPROVED** [review]
👍

**Comment by anthrotype** [comment]
just curious, did something not work with manylinux1 that prompted the switch to the 2014 manylinyx image? the former wheel tag has wider support than the latter (older pips and linux versions)

**Comment by kaydeearts** [comment]
@anthrotype Yes, we switched from manylinux1 to manylinux2014 after running into problems with the `libuuid-devel` library being installed but not found within the wheel. Since manylinux1 is based on CentOS5 which was deprecated in 2017, updating to the current manylinux2014 tag (based on CentOS7) fixed that problem.

**Comment by anthrotype** [comment]
ok thanks for the clarification

**Pull request merged**
