### PR TITLE
[checkOutlinesUFO] Re-write the in-line help formatter so that it is …

### PR DESCRIPTION
**Pull request by readroberts**
…not a direct copy of the StackOverflow example

The StackOverflow license is viral. We can use code snippets as examples, but cannot directly copy code. We most certainly cannot include complete URLs that reference a StackOverflow example.

### CODE REVIEW

**Comment by miguelsousa** [comment]
@readroberts is there a particular reason why you moved the `add_whitespace` method outside of the class?

**Comment by readroberts** [comment]
@msousa @cjchapman I moved the 'add_whitespace' from a class method to a function because that is one of the flake8 complaints. Since 'add_whitespace' code never references 'self', and is not an inherited method, it does not need to be a method.

There is an outstanding Codacy warning that I don't know how to fix. The warning is that the arguments to the '_split_lines' method do not match the arguments to the inherited method. However, they do in fact match the arguments to the  parent class 'argparse.RawDescriptionHelpFormatter'. Chris, do you have any ideas about this?

**Comment by miguelsousa** [comment]
> Since 'add_whitespace' code never references 'self', and is not an inherited method, it does not need to be a method.

That can be fixed by placing `@staticmethod` above the class method.

**Comment by cjchapman** [comment]
@readroberts & @miguelsousa I can confirm that the super method for `_splint_lines` has the same arguments:
```python
class HelpFormatter(object):
...
    def _split_lines(self, text, width):
```
...so I recommend that we just ignore the spurious error for now, and disable it if we get many more false positives like this.

**Pull request merged**
